### ISSUE TITLE
自动生成作者卡片没有工作

### ISSUE THREAD

**Issue by stuffed-cat** [pysio2007/Vue-blog#90]
<img width="488" alt="image" src="https://github.com/user-attachments/assets/a5311933-89e2-4f7c-9204-a012f8e9f4aa">
<img width="200" alt="image" src="https://github.com/user-attachments/assets/bb926442-b809-4062-9843-933241c1e86c">
 
构建版本 a6ac21a

**Comment by pysio2007** [comment]
有空在修（x 先手动加

**Comment by pysio2007** [comment]
根据 #91 https://github.com/pysio2007/Vue-blog/pull/91#issue-2615909474 此Issues很长一段时间无修复Commit 更何况设计CI/DI的替换= =
